### ISSUE TITLE
Host cpu_match attr is ignored if Global cpu_mode attr is set

### ISSUE THREAD

**Issue by tcooper** [rocksclusters/kvm#11]
If the global attribute, `cpu_mode`, is set then the host attribute, `cpu_match`, is ignored/overwritten when generating the libvirt XML configuration for a KVM guest.

- List the **default** cpu related attributes for a KVM guest ([set here](https://github.com/rocksclusters/kvm/blob/fe736a5943e57219850577a8416e46a6a72eb55e/nodes/kvm-server-db-data.xml#L48))...
```
[root@cluster config]# rocks list host attr vcn-1-11 | egrep "cpu_m"
vcn-1-11: cpu_mode      host-passthrough                                               G
```
- Report the **default** XML configuration for a KVM guest...
```
[root@cluster config]# rocks report host vm config vcn-1-11 | grep "cpu mode" -B1 -A1
  <vcpu>24</vcpu>
  <cpu mode='host-passthrough'/>
  <cputune>
 ```
- Add a host `cpu_match` attribute to the KVM guest...
```
[root@cluster config]# rocks add host attr vcn-1-11 cpu_match \
    value="host-passthrough:<topology sockets='2' cores='12' threads='1'/>"
```
- List host attributes of the KVM guest...
```
[root@cluster config]# rocks list host attr vcn-1-11 | egrep "cpu_m"
vcn-1-11: cpu_match     host-passthrough:<topology sockets='2' cores='12' threads='1'/> 
                                                                                       H
vcn-1-11: cpu_mode      host-passthrough                                               G
```
- Report the libvirt XML configuration of the KVM guest... 
```
[root@cluster config]# rocks report host vm config vcn-1-11 | grep "cpu mode" -B1 -A1
  <vcpu>24</vcpu>
  <cpu mode='host-passthrough'/>
  <cputune>
```
**NOTE: The topology configuration is not there.**

- Remove global cpu_mode attribute  
```
[root@cluster config]# rocks remove attr cpu_mode
```
- List host attributes of the KVM guest...
```
[root@cluster config]# rocks list host attr vcn-1-11 | egrep "cpu_m"
vcn-1-11: cpu_match     host-passthrough:<topology sockets='2' cores='12' threads='1'/>
                                                                                       H
```
- Report xml config of the KVM guest...
```
[root@cluster config]# rocks report host vm config vcn-1-11 | grep "cpu mode" -B1 -A2
  <vcpu>24</vcpu>
  <cpu mode='host-passthrough'>
<topology sockets='2' cores='12' threads='1'/>
  </cpu>
```
**NOTE: The topology configuration is now reported**

**Comment by lclementi** [comment]
https://github.com/rocksclusters/kvm/commit/4c123a0435ceffb429880c914be8a1a84c8114aa

fixed
